"use client";
import { useState } from "react"; import { useRouter } from "next/navigation";
type Product = { title?: string; priceMinor?: number; regularPriceMinor?: number; currency?: string; availability: string; imageUrl?: string; hostname: string; detectionMethod: string };
type Initial = { id?: string; name?: string; url?: string; hostname?: string; imageUrl?: string | null; checkIntervalMinutes?: number; targetPriceMinor?: number | null; enabled?: boolean; notifyOnPriceDrop?: boolean; notifyOnTargetPrice?: boolean; notifyOnAvailable?: boolean; notifyOnUnavailable?: boolean; notifyOnPriceIncrease?: boolean; browserMode?: boolean; confirmationCount?: number; notificationCooldownMinutes?: number; priceSelector?: string | null; availabilitySelector?: string | null };
export function BotForm({ initial = {} }: { initial?: Initial }) {
  const router = useRouter(); const [url, setUrl] = useState(initial.url ?? ""); const [product, setProduct] = useState<Product | null>(initial.id ? { title: initial.name, hostname: initial.hostname ?? "", imageUrl: initial.imageUrl ?? undefined, availability: "UNKNOWN", detectionMethod: "HTML_TEXT" } : null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const analyze = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message); setProduct(body.product); } catch (e) { setError(e instanceof Error ? e.message : "Analysis failed."); } finally { setLoading(false); } };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const dollars = Number(data.get("targetPrice") || 0); const body = { name: String(data.get("name")), url, hostname: product?.hostname ?? new URL(url).hostname, imageUrl: product?.imageUrl ?? null, enabled: true, checkIntervalMinutes: Number(data.get("interval")), browserMode: data.get("browserMode") === "on", notifyOnPriceDrop: data.get("priceDrop") === "on", notifyOnTargetPrice: data.get("target") === "on", targetPriceMinor: dollars ? Math.round(dollars * 100) : null, notifyOnAvailable: data.get("available") === "on", notifyOnUnavailable: data.get("unavailable") === "on", notifyOnPriceIncrease: data.get("increase") === "on", minimumChangeMinor: 1, minimumChangePercent: 0, confirmationCount: Number(data.get("confirmationCount")), notificationCooldownMinutes: Number(data.get("cooldown")), pageLoadDelayMs: 0, priceSelector: String(data.get("priceSelector") || "") || null, availabilitySelector: String(data.get("availabilitySelector") || "") || null, channelIds: [] };
    const response = await fetch(initial.id ? `/api/bots/${initial.id}` : "/api/bots", { method: initial.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) return setError(result.error?.message ?? "Could not save bot."); router.push("/"); router.refresh(); };
  return <form className="formStack" onSubmit={submit}><section className="formCard"><div className="step"><span>1</span><div><h2>Product page</h2><p>We’ll look for structured product data first, then inspect the page.</p></div></div><label>Product URL<div className="analyzeRow"><input type="url" required value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://store.example.com/product" /><button type="button" className="button secondary" onClick={analyze} disabled={loading || !url}>{loading ? "Analyzing…" : "Analyze Page"}</button></div></label>{error && <p className="formError">{error}</p>}</section>
  {product && <><section className="formCard detected"><div className="step"><span>✓</span><div><h2>Product detected</h2><p>Review these details before saving.</p></div></div><div className="detectedGrid"><div className="previewImage">{product.imageUrl ? <img src={product.imageUrl} alt="" /> : "↘"}</div><label>Product name<input name="name" required defaultValue={product.title} /></label><div className="detectStat"><span>Price</span><strong>{product.priceMinor == null ? "Not found" : new Intl.NumberFormat(undefined, { style: "currency", currency: product.currency ?? "USD" }).format(product.priceMinor / 100)}</strong></div><div className="detectStat"><span>Availability</span><strong>{product.availability.replaceAll("_", " ")}</strong></div><div className="detectStat"><span>Detection</span><strong>{product.detectionMethod.replaceAll("_", " ")}</strong></div></div></section>
  <section className="formCard"><div className="step"><span>2</span><div><h2>Monitoring rules</h2><p>Choose what should wake you up.</p></div></div><div className="checkGrid"><label className="check"><input name="priceDrop" type="checkbox" defaultChecked={initial.notifyOnPriceDrop ?? true} /><span><b>Any price drop</b><small>Notify when the price moves down</small></span></label><label className="check"><input name="available" type="checkbox" defaultChecked={initial.notifyOnAvailable ?? true} /><span><b>Back in stock</b><small>Notify when availability returns</small></span></label><label className="check"><input name="target" type="checkbox" defaultChecked={initial.notifyOnTargetPrice} /><span><b>Target price</b><small>Alert at or below your threshold</small></span></label><label className="check"><input name="unavailable" type="checkbox" defaultChecked={initial.notifyOnUnavailable} /><span><b>Goes out of stock</b><small>Optional availability warning</small></span></label></div><div className="fieldGrid"><label>Target price<input name="targetPrice" type="number" min="0" step=".01" defaultValue={initial.targetPriceMinor ? initial.targetPriceMinor / 100 : ""} placeholder="99.00" /></label><label>Check interval<select name="interval" defaultValue={initial.checkIntervalMinutes ?? 30}>{[[5,"5 minutes"],[10,"10 minutes"],[15,"15 minutes"],[30,"30 minutes"],[60,"1 hour"],[120,"2 hours"],[240,"4 hours"],[480,"8 hours"],[720,"12 hours"],[1440,"24 hours"]].map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></label><label>Confirmations<select name="confirmationCount" defaultValue={initial.confirmationCount ?? 2}><option value="1">1 result</option><option value="2">2 results (recommended)</option><option value="3">3 results</option></select></label><label>Cooldown (minutes)<input name="cooldown" type="number" min="0" defaultValue={initial.notificationCooldownMinutes ?? 60} /></label></div></section>
  <details className="formCard"><summary>Advanced detection</summary><div className="fieldGrid advanced"><label>Price CSS selector<input name="priceSelector" defaultValue={initial.priceSelector ?? ""} placeholder=".product-price" /></label><label>Availability selector<input name="availabilitySelector" defaultValue={initial.availabilitySelector ?? ""} placeholder="[itemprop=availability]" /></label><label className="check inline"><input name="browserMode" type="checkbox" defaultChecked={initial.browserMode} /><span><b>Browser rendering</b><small>Use only for JavaScript-rendered pages</small></span></label><label className="check inline"><input name="increase" type="checkbox" defaultChecked={initial.notifyOnPriceIncrease} /><span><b>Price increases</b><small>Disabled by default</small></span></label></div></details>
  <div className="formActions"><button type="button" className="button ghost" onClick={() => router.back()}>Cancel</button><button className="button primary" type="submit">{initial.id ? "Save changes" : "Create Bot"}</button></div></>}</form>;
}
