"use client";
import Link from "next/link";
import { useMemo, useState } from "react";

type State = { priceMinor: number | null; currency: string | null; availability: string; checkedAt: string; confirmed?: boolean; reachable?: boolean | null; responseTimeMs?: number | null; numericValue?: number | null };
type Bot = { id: string; name: string; hostname: string; imageUrl: string | null; enabled: boolean; monitorKind?: "PRODUCT" | "HTTP" | "TCP" | "VALUE"; tcpPort?: number | null; latencyThresholdMs?: number; valueLabel?:string|null; valueUnit?:string|null; alertAbove?:number|null; alertBelow?:number|null; targetPriceMinor: number | null; lastCheckAt: string | null; nextCheckAt: string; lastError: string | null; consecutiveErrors?: number; variantName?: string | null; variantValue?: string | null; states: State[] };
const money = (minor: number | null | undefined, currency = "USD") => minor == null ? "—" : new Intl.NumberFormat(undefined,{style:"currency",currency}).format(minor/100);
const time = (value: string | null) => value ? new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "Never";

export function Dashboard({ initialBots }: { initialBots: Bot[] }) {
  const [bots,setBots] = useState(initialBots); const [busy,setBusy] = useState(""); const [toast,setToast] = useState(""); const [query,setQuery] = useState(""); const [filter,setFilter] = useState("all"); const [sort,setSort] = useState("newest"); const [selected,setSelected] = useState<string[]>([]);
  const current = (bot:Bot) => bot.states[0];
  const visible = useMemo(() => bots.filter((bot) => `${bot.name} ${bot.hostname} ${bot.variantValue??""}`.toLowerCase().includes(query.toLowerCase())).filter((bot) => filter==="all" || filter==="active"&&bot.enabled || filter==="paused"&&!bot.enabled || filter==="errors"&&bot.lastError || filter==="stock"&&current(bot)?.availability==="IN_STOCK").sort((a,b) => sort==="name"?a.name.localeCompare(b.name):sort==="price"?(current(a)?.priceMinor??Infinity)-(current(b)?.priceMinor??Infinity):new Date(b.nextCheckAt).getTime()-new Date(a.nextCheckAt).getTime()),[bots,query,filter,sort]);
  const act = async(id:string,action:string) => { setBusy(id+action); const response=await fetch(`/api/bots/${id}/${action}`,{method:"POST"}); const body=await response.json(); setToast(response.ok?action==="check"?"Check completed.":`Bot ${action}d.`:body.error?.message); if(response.ok) location.reload(); else setBusy(""); };
  const bulk = async(action:"check"|"pause"|"resume") => { if(!selected.length)return; setBusy("bulk"); const results=await Promise.all(selected.map(id=>fetch(`/api/bots/${id}/${action}`,{method:"POST"}))); setToast(`${results.filter(r=>r.ok).length} of ${results.length} bots updated.`); location.reload(); };
  const remove=async(id:string)=>{if(!confirm("Delete this bot and all of its history?"))return;const response=await fetch(`/api/bots/${id}`,{method:"DELETE"});if(response.ok)setBots(v=>v.filter(b=>b.id!==id));};
  const summary=[["Total bots",bots.length,"All configured monitors"],["Active",bots.filter(b=>b.enabled).length,"Scheduled and running"],["In stock",bots.filter(b=>current(b)?.availability==="IN_STOCK").length,"Available right now"],["At target",bots.filter(b=>b.targetPriceMinor!=null&&(current(b)?.priceMinor??Infinity)<=b.targetPriceMinor!).length,"Ready to buy"],["Need attention",bots.filter(b=>b.lastError).length,"Reporting errors"]];
  return <><section className="pageHead"><div><p className="eyebrow">Smart monitoring</p><h1>Your watchlist</h1><p>Track products, webpage values, websites, and servers from one dashboard.</p></div><div className="formActions"><Link href="/bots/new/value" className="button ghost">＋ Value Monitor</Link><Link href="/bots/new/uptime" className="button secondary">＋ Uptime Monitor</Link><Link href="/bots/new" className="button primary">＋ Product Bot</Link></div></section>
    <section className="summaryGrid">{summary.map(([label,value,note])=><article className="summary" key={String(label)}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
    <section className="panel"><div className="panelHead"><div><h2>Monitoring</h2><p>{bots.length?`${bots.filter(b=>b.enabled).length} bots are active`:"Add your first product to begin"}</p></div><span className="live">● Scheduler online</span></div>
      {bots.length>0&&<div className="toolbar"><input aria-label="Search bots" placeholder="Search products or stores…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter bots" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All bots</option><option value="active">Active</option><option value="paused">Paused</option><option value="stock">In stock</option><option value="errors">Errors</option></select><select aria-label="Sort bots" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Next check</option><option value="name">Name</option><option value="price">Lowest price</option></select><div className="bulkActions"><button className="button tiny" disabled={!selected.length||busy==="bulk"} onClick={()=>bulk("check")}>Check selected</button><button className="button tiny" disabled={!selected.length} onClick={()=>bulk("pause")}>Pause</button><button className="button tiny" disabled={!selected.length} onClick={()=>bulk("resume")}>Resume</button></div></div>}
      {!bots.length?<div className="empty"><div className="emptyIcon">↘</div><h3>No monitors yet</h3><p>Add a product, webpage value, website, or server to begin monitoring.</p><Link href="/bots/new/value" className="button primary">Add your first monitor</Link></div>:!visible.length?<div className="miniEmpty">No bots match these filters.</div>:<div className="botList">{visible.map(bot=>{
        const state=current(bot),previous=bot.states[1]; const uptime=bot.monitorKind==="HTTP"||bot.monitorKind==="TCP"; const value=bot.monitorKind==="VALUE";
        const currentMetric=value?(state?.numericValue!=null?`${state.numericValue}${bot.valueUnit??""}`:"—"):uptime?(state?.responseTimeMs!=null?`${state.responseTimeMs} ms`:"—"):money(state?.priceMinor,state?.currency??"USD");
        const previousMetric=value?(previous?.numericValue!=null?`was ${previous.numericValue}${bot.valueUnit??""}`:"No previous value"):uptime?(previous?.responseTimeMs!=null?`was ${previous.responseTimeMs} ms`:"No previous check"):(previous?`was ${money(previous.priceMinor,previous.currency??"USD")}`:"No previous price");
        return <article className="botRow selectable" key={bot.id}><input className="rowSelect" type="checkbox" aria-label={`Select ${bot.name}`} checked={selected.includes(bot.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,bot.id]:v.filter(id=>id!==bot.id))}/><div className="productThumb">{bot.imageUrl?<img src={bot.imageUrl} alt=""/>:<span>{uptime?"●":value?"#":"↘"}</span>}</div><div className="productInfo"><h3>{bot.name}</h3><p>{bot.hostname}{bot.tcpPort?`:${bot.tcpPort}`:""}{bot.variantValue?` · ${bot.variantName??"Variant"}: ${bot.variantValue}`:""}</p><div className="badges"><span className={`badge ${bot.enabled?"healthy":"muted"}`}>{bot.enabled?"Active":"Paused"}</span>{uptime&&<span className={`badge ${state?.reachable===true?"healthy":state?.reachable===false?"danger":"muted"}`}>{state?.reachable===true?"ONLINE":state?.reachable===false?"OFFLINE":"UNKNOWN"}</span>}{value&&<span className="badge muted">VALUE</span>}{!uptime&&!value&&<span className={`badge ${state?.availability==="IN_STOCK"?"healthy":state?.availability==="OUT_OF_STOCK"?"danger":"muted"}`}>{state?.availability?.replaceAll("_"," ")??"UNKNOWN"}</span>}{bot.lastError&&<span className="badge danger">Error</span>}</div></div><div className="metric"><span>{value?bot.valueLabel??"Current value":uptime?"Response time":"Current price"}</span><strong>{currentMetric}</strong><small>{previousMetric}</small></div><div className="metric"><span>{value?"Alert range":uptime?"Slow threshold":"Target"}</span><strong>{value?`${bot.alertBelow??"—"} – ${bot.alertAbove??"—"}${bot.valueUnit??""}`:uptime?`${bot.latencyThresholdMs??1000} ms`:money(bot.targetPriceMinor,state?.currency??"USD")}</strong><small>{value?"Numeric URL monitor":uptime?`${bot.monitorKind} monitor`:(bot.targetPriceMinor?"Alert threshold":"Not set")}</small></div><div className="metric schedule"><span>Last checked</span><strong>{time(bot.lastCheckAt)}</strong><small>{bot.enabled?`Next ${time(bot.nextCheckAt)}`:"Scheduling paused"}</small>{bot.lastError&&<em>{bot.lastError}</em>}</div><div className="rowActions"><button className="iconButton" title="Check now" disabled={busy===bot.id+"check"} onClick={()=>act(bot.id,"check")}>↻</button><button className="iconButton" title={bot.enabled?"Pause":"Resume"} onClick={()=>act(bot.id,bot.enabled?"pause":"resume")}>{bot.enabled?"Ⅱ":"▶"}</button><Link className="iconButton" title="Edit and view health" href={`/bots/${bot.id}`}>✎</Link><button className="iconButton dangerText" title="Delete" onClick={()=>remove(bot.id)}>×</button></div></article>})}</div>}</section>{toast&&<div className="toast" role="status" onClick={()=>setToast("")}>{toast}</div>}</>;
}
