"use client";
import { useMemo, useState } from "react";
import { Brush, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type State = { id: string; checkedAt: string; priceMinor: number | null; currency: string | null; availability: string; detectionMethod: string; warning: string | null; confirmed: boolean; reachable?: boolean | null; responseTimeMs?: number | null; numericValue?:number|null };
export function HistoryChart({ states, targetPriceMinor, uptime = false, latencyThresholdMs, valueMonitor=false, valueUnit="", alertAbove, alertBelow }: { states: State[]; targetPriceMinor: number | null; uptime?: boolean; latencyThresholdMs?: number; valueMonitor?:boolean; valueUnit?:string|null; alertAbove?:number|null; alertBelow?:number|null }) {
  const [range, setRange] = useState(uptime ? "24h" : "30d");
  const data = useMemo(() => { const newest = states.length ? new Date(states[0].checkedAt).getTime() : 0; const durations: Record<string,number> = { "1h":3600000,"24h":86400000,"7d":604800000,"30d":2592000000,"90d":7776000000 }; const cutoff = range === "all" ? 0 : newest - durations[range]; return states.filter((s) => new Date(s.checkedAt).getTime() >= cutoff && (valueMonitor?s.numericValue!=null:uptime ? s.responseTimeMs != null : s.priceMinor != null)).map((s) => ({ ...s, date: new Date(s.checkedAt).toLocaleString([], range === "1h" || range === "24h" ? {hour:"numeric",minute:"2-digit"}:{month:"short",day:"numeric"}), value: valueMonitor?s.numericValue!:uptime ? s.responseTimeMs! : s.priceMinor! / 100 })).reverse(); }, [states, range, uptime, valueMonitor]);
  const stats = useMemo(() => { const values=data.filter((item)=>item.reachable!==false).map((item)=>item.value); return values.length ? { min:Math.min(...values), max:Math.max(...values), average:Math.round(values.reduce((sum,value)=>sum+value,0)/values.length), uptime:Math.round(data.filter((item)=>item.reachable!==false).length/data.length*10000)/100 } : null; },[data]);
  const currency = states.find((state) => state.currency)?.currency ?? "USD";
  return <section className="formCard historyCard"><div className="historyHead"><div><p className="eyebrow">Timeline</p><h2>{valueMonitor?"Value history":uptime ? "Response-time history" : "Price history"}</h2></div><select value={range} onChange={(event) => setRange(event.target.value)} aria-label="History range">{(uptime||valueMonitor)&&<><option value="1h">Last hour</option><option value="24h">Last 24 hours</option></>}<option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option><option value="all">All time</option></select></div>
    {uptime&&stats&&<div className="chartStats"><span>Uptime <b>{stats.uptime}%</b></span><span>Average <b>{stats.average} ms</b></span><span>Minimum <b>{stats.min} ms</b></span><span>Maximum <b>{stats.max} ms</b></span></div>}
    {data.length ? <div className="chartWrap"><ResponsiveContainer width="100%" height={285}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={.18}/><XAxis dataKey="date" tick={{ fontSize: 11 }}/><YAxis tick={{ fontSize: 11 }} domain={["auto","auto"]}/><Tooltip formatter={(value) => valueMonitor?`${value}${valueUnit??""}`:uptime ? `${value} ms` : new Intl.NumberFormat(undefined,{style:"currency",currency}).format(Number(value))}/>{valueMonitor&&alertAbove!=null&&<ReferenceLine y={alertAbove} stroke="#ef4d2f" strokeDasharray="5 5" label="Above"/>}{valueMonitor&&alertBelow!=null&&<ReferenceLine y={alertBelow} stroke="#3567c8" strokeDasharray="5 5" label="Below"/>}{uptime && latencyThresholdMs != null ? <ReferenceLine y={latencyThresholdMs} stroke="#ef4d2f" strokeDasharray="5 5" label="Slow"/> : !valueMonitor&&targetPriceMinor != null && <ReferenceLine y={targetPriceMinor/100} stroke="#ef4d2f" strokeDasharray="5 5" label="Target"/>}<Line type="monotone" dataKey="value" stroke="#ef4d2f" strokeWidth={3} dot={data.length<100?{r:3}:false}/><Brush dataKey="date" height={24} travellerWidth={8}/></LineChart></ResponsiveContainer></div> : <div className="miniEmpty">{valueMonitor?"Value history":uptime ? "Response-time history" : "Price history"} will appear after successful checks.</div>}
    <div className="historyTable">{states.slice(0,12).map((state) => <div key={state.id}><span>{new Date(state.checkedAt).toLocaleString()}</span><b>{valueMonitor?state.numericValue==null?"—":`${state.numericValue}${valueUnit??""}`:uptime ? state.responseTimeMs == null ? "—" : `${state.responseTimeMs} ms` : state.priceMinor == null ? "—" : new Intl.NumberFormat(undefined,{style:"currency",currency:state.currency??"USD"}).format(state.priceMinor/100)}</b><span className={`badge ${state.availability==="IN_STOCK"?"healthy":state.availability==="OUT_OF_STOCK"?"danger":"muted"}`}>{valueMonitor?"RECORDED":uptime ? state.reachable ? "ONLINE" : "OFFLINE" : state.availability.replaceAll("_"," ")}</span><small>{state.confirmed ? state.detectionMethod.replaceAll("_"," ") : "Pending confirmation"}</small></div>)}</div>
  </section>;
}
