"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Initial = { id:string; name:string; url:string; hostname:string; valueLabel:string|null; valueUnit:string|null; valueSelector:string|null; alertAbove:number|null; alertBelow:number|null; notifyOnValueChange:boolean; minimumValueChange:number; checkIntervalMinutes:number; checkIntervalSeconds:number; notificationCooldownMinutes:number; enabled:boolean; channels?:{notificationChannelId:string}[] };
export function ValueForm({initial}:{initial?:Initial}) {
  const router=useRouter(); const [error,setError]=useState("");
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");const data=new FormData(event.currentTarget);let url=String(data.get("url")).trim();if(!/^https?:\/\//i.test(url))url=`https://${url}`;let hostname="";try{hostname=new URL(url).hostname;}catch{return setError("Enter a valid webpage address.");}const interval=Number(data.get("interval"));const optionalNumber=(name:string)=>{const value=String(data.get(name)??"").trim();return value===""?null:Number(value);};const body={name:String(data.get("name")),url,hostname,monitorKind:"VALUE",tcpPort:null,latencyThresholdMs:1000,notifyOnDown:false,notifyOnRecovery:false,notifyOnHighLatency:false,failureConfirmationCount:1,reminderIntervalMinutes:0,expectedContent:null,dnsMonitoring:false,sslMonitoring:false,sslExpiryWarningDays:30,valueLabel:String(data.get("valueLabel")||"")||null,valueUnit:String(data.get("valueUnit")||"")||null,valueSelector:String(data.get("valueSelector")||"")||null,alertAbove:optionalNumber("alertAbove"),alertBelow:optionalNumber("alertBelow"),notifyOnValueChange:data.get("notifyOnValueChange")==="on",minimumValueChange:Number(data.get("minimumValueChange")||0),enabled:initial?.enabled??true,checkIntervalMinutes:Math.max(1,Math.ceil(interval/60)),checkIntervalSeconds:interval,browserMode:false,notifyOnPriceDrop:false,notifyOnTargetPrice:false,targetPriceMinor:null,notifyOnAvailable:false,notifyOnUnavailable:false,notifyOnPriceIncrease:false,minimumChangeMinor:1,minimumChangePercent:0,confirmationCount:1,notificationCooldownMinutes:Number(data.get("cooldown")),pageLoadDelayMs:0,channelIds:initial?.channels?.map((channel)=>channel.notificationChannelId)??[]};const response=await fetch(initial?`/api/bots/${initial.id}`:"/api/bots",{method:initial?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)return setError(result.error?.message??"Could not save value monitor.");router.push(`/bots/${result.bot.id}`);router.refresh();};
  return <form className="formStack" onSubmit={submit}><section className="formCard"><div className="step"><span>1</span><div><h2>Value source</h2><p>Watch any numeric value published on a webpage.</p></div></div><div className="fieldGrid"><label>Monitor name<input name="name" required defaultValue={initial?.name} placeholder="Federal funds rate"/></label><label>Webpage URL<input name="url" required defaultValue={initial?.url} placeholder="example.com/rates"/></label><label>Value name<input name="valueLabel" required defaultValue={initial?.valueLabel??""} placeholder="Interest rate"/></label><label>Unit<input name="valueUnit" defaultValue={initial?.valueUnit??"%"} placeholder="%, °F, USD"/></label><label>CSS selector (optional)<input name="valueSelector" defaultValue={initial?.valueSelector??""} placeholder=".current-rate"/></label></div><p className="help">For the most reliable result, enter a CSS selector. Without one, Bots searches near the value name and then uses the first percentage on the page.</p></section><section className="formCard"><div className="step"><span>2</span><div><h2>Alert rules</h2><p>Notify when the value crosses a limit or changes.</p></div></div><div className="checkGrid"><label className="check"><input name="notifyOnValueChange" type="checkbox" defaultChecked={initial?.notifyOnValueChange}/><span><b>Value changes</b><small>Alert when the change meets your minimum</small></span></label></div><div className="fieldGrid"><label>Alert above<input name="alertAbove" type="number" step="any" defaultValue={initial?.alertAbove??""} placeholder="7.0"/></label><label>Alert below<input name="alertBelow" type="number" step="any" defaultValue={initial?.alertBelow??""} placeholder="5.0"/></label><label>Minimum change<input name="minimumValueChange" type="number" min="0" step="any" defaultValue={initial?.minimumValueChange??0.01}/></label><label>Check interval<select name="interval" defaultValue={initial?.checkIntervalSeconds??1800}><option value="60">1 minute</option><option value="300">5 minutes</option><option value="900">15 minutes</option><option value="1800">30 minutes</option><option value="3600">1 hour</option><option value="21600">6 hours</option><option value="86400">24 hours</option></select></label><label>Notification cooldown (minutes)<input name="cooldown" type="number" min="0" max="10080" defaultValue={initial?.notificationCooldownMinutes??60}/></label></div>{error&&<p className="formError">{error}</p>}</section><div className="formActions"><button type="button" className="button ghost" onClick={()=>router.back()}>Cancel</button><button className="button primary">{initial?"Save Value Monitor":"Create Value Monitor"}</button></div></form>;
}
